### ISSUE TITLE
Chargement .ics sur Android 

### ISSUE THREAD

**Issue by MichaelDclr** [AVapps/tosync#9]
Bonjour Adrien,

Le chargement du fichier ics fonctionne parfaitement sur mon iPad, par contre impossible sur Android.

J'ai le message d'erreur suivant :
![Screenshot_20220129-111632](https://user-images.githubusercontent.com/98642711/151657379-5573c13d-c77d-4bf6-a1d5-342e1f811b3c.jpg)

Je suis disponible pour t'aider à résoudre ce problème.

Merci beaucoup pour ton outils indispensable,
Bonne journée 😉

**Comment by AVapps** [comment]
Salut Michaël, pourrais-tu m'envoyer le fichier iCalendar qui pose problème ? Malheureusement je n'ai toujours pas de téléphone ou tablette Android donc j'aurais effectivement besoin de ton aide si je sèche.

**Comment by MichaelDclr** [comment]
Salut Andrien,
Je t'envoie le fichier par email.
Pour info, j'ai un problème d'obtention du fichier ics sur l'iPad via Safari.
Pour faire la manip correctement, je dois récupérer le fichier ics via Chrome sur mon iPad, puis le charger dans TO Sync.
